require("dotenv").config();

const {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY,
  PORT,
  BONUM_API_BASE_URL,
  BONUM_APP_SECRET,
  BONUM_TERMINAL_ID,
  BONUM_WEBHOOK_CHECKSUM_KEY,
  BONUM_INVOICE_CALLBACK_URL,
} = process.env;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error("Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env");
}

module.exports = {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY,
  PORT,
  BONUM_API_BASE_URL,
  BONUM_APP_SECRET,
  BONUM_TERMINAL_ID,
  BONUM_WEBHOOK_CHECKSUM_KEY,
  BONUM_INVOICE_CALLBACK_URL,
};
